language: python

python:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - echo "not running xvfb start"
  - sudo apt-get install pep8 -y

script: 
  - python run-tests.py
  - bash coverage.sh

after_success: coveralls